# Generated by Django 5.2 on 2025-04-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_uploadedreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedreport',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_reports/'),
        ),
    ]
